#server setting
server:
  port: 80
  tomcat:
    uri-encoding: utf-8
    #最大连接数
    max-connections: 10000
    #最大线程数，最大并发数
    max-threads: 1000
    #最小备用线程数
    min-spare-threads: 20
    #线程数达到maxThreads后，后续请求会被放入一个等待队列，accept-count是这个队列的大小
    accept-count: 500
    #是否开启access log ，默认: false
    accesslog:
      enabled: true
  connection-timeout: 1800
spring:
  application:
      name: fuhui
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_default
  thymeleaf:
    # 关闭thymeleaf缓存 开发时使用 否则没有实时画面
    cache: false
    # 检查模板是否存在，然后再呈现
    check-template-location: true
    # Content-Type value.
    content-type: text/html
    # 启用MVC Thymeleaf视图分辨率
    enabled: true
    # Template encoding.
    encoding: UTF-8
    # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    mode: LEGACYHTML5
    # Prefix that gets prepended to view names when building a URL.
    prefix: classpath:/templates/
    # Suffix that gets appended to view names when building a URL.
    suffix: .html
    #thymeleaf end
  # JPA Configuration
  mvc:
    # 指定静态资源处理路径
    static-path-pattern: /static/**
    view:
      suffix: .html
  jpa:
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    generate-ddl: true
    # spring.jpa.database=org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://rm-uf6scm3ghrqkk306w9o.mysql.rds.aliyuncs.com:3306/nuojin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      name: root
      password: wsy@123456
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
logging:
  level:
    org.springframework.web: INFO
    com.fsg.salary: INFO
  pattern:
    level: INFO
  file: /var/log/fuhui.log
#公众号配置
wechat:
  mp:
    appId: wxea7b5c253702db34
    secret: 5bbd5b14df3a196784076a806bd9fbc1
    token: TdbjScsWLoRDLRFYLA27in6o9YSOa6vI
    aesKey: